spring:
  profiles:
    group:
      test: "test"
  application:
    name: stonebed

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /walwal-actuator
    jmx:
      exposure:
        exclude: "*"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true

api:
  version: "0.0.1"
