spring:
  profiles:
    group:
      test: "test"
      local: "local, datasource"
      dev: "dev, datasource"
      prod: "prod, datasource"
    include:
      - redis
      - actuator
      - docs
      - cloud
      - security
  application:
    name: stonebed

logging:
  level:
    com.depromeet.stonebed.*.*.api.*: debug
    com.depromeet.stonebed.*.*.application.*: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

fcm:
  credential: ${FCM_CREDENTIAL}
